project='reactos'; license='GNU General Public License / GNU Lesser General Public License Version 3'
project='FFmpeg'; license='GNU Lesser General Public License version 2.1 or later (LGPL v2.1+).'
project='darwin-xnu'; license='APPLE PUBLIC SOURCE LICENSE Version 2.0'
project='php-kdb'; license='GPL version 2 or later'
project='git'; license='GNU General Public License version 2 (some parts of it are under different licenses, compatible with the GPLv2'
project='radare2'; license='GNU Lesser General Public License v3.0'
project='lab'; license='GNU General Public License Version v2.0'
project='openssl'; license='Apache License 2.0'
project='obs-studio'; license='GNU General Public License v2 (or any later version)'
project='libgit2'; license='GPLv2 with a special Linking Exception)'
project='emscripten'; license='MIT license and the University of Illinois/NCSA Open Source License'
project='php-src'; license='The PHP License, version 3.01'
project='softEtherVPN'; license='Apache License Version 2.0'
project='h20'; license='MIT License'
project='mph'; license='GPLv2 or later by default, LGPLv2.1 "or later" with --enable-lgpl'
project='redis'; license='BSD 3-Clause “New” or “Revised” License'
project='Nodemcu'; license='MIT License'
project='mongoose'; license='MIT License'